### ISSUE TITLE
Could not resolve host: server.localhost.me

### ISSUE THREAD

**Issue by BlazeWasHere** [FluxedScript/PNA#1]
https://github.com/FluxedScript/PNA/blob/8f76e8190e1636784937ba8506ba84f21cdac7bc/nertivia/bot.py#L18

This does not work for me, and probably the same for others.

```sh
curl server.localhost.me
curl: (6) Could not resolve host: server.localhost.me
```

**Comment by FluxedScript** [comment]
Please have a look at https://github.com/Nertivia-Compose/instance

**Comment by BlazeWasHere** [comment]
which part of it?
